name: godlessglen
favicon: null
layout_spectrum: 0.012255296343937516
typography_spectrum: 0.006729412125423551
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9647426388692111
  lightness: 0.6399524547159672
  saturation: 0.8625372056849301
  rhythmicContrast: 0.25434370432049036
purpose: []
